# Generated by Django 5.0.6 on 2024-06-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewslatter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslatteremail',
            name='userEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
