# Generated by Django 5.0.6 on 2024-06-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='stauts_message',
            new_name='status_message',
        ),
    ]
